### ISSUE TITLE
Logs page is incomplete

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/docs#103]
[This logs page](https://gluu.org/docs/gluu-defaults/logs/) needs work.

1. The logs page has a list of logs, but no description what is contained in each.
2. What about LDAP logs? /opt/opendj/logs ? 
3. If cache refresh or external LDAP authentication, what about logs of the target LDAP servers?
4. Apache web server logs?

**Comment by mzico** [comment]
@nynymike : Checking status.

**Comment by aliaksander-samuseu** [comment]
@mzico 

Here my humble attempt to write a logging article while back: [link](https://wiki.gluu.info/doku.php?id=appliance:logging&s[]=logging)
It's incomplete and full of holes, so needs polishing at least.

**Comment by mzico** [comment]
Thanks @aliaksander-samuseu; we will add points and description in your doc then.

**Comment by mzico** [comment]
@nynymike : [This](https://ox.gluu.org/doku.php?id=ce:logs) is the starting condition.

**Comment by willow9886** [comment]
@mzico should we update our public docs?

**Comment by mzico** [comment]
@willow9886 : Not yet... please allow me to finish this. My plan is to add little example snippets along with description.

**Comment by willow9886** [comment]
sounds good.

**Comment by mzico** [comment]
@nynymike @willow9886 @zamilskhan : New doc on Gluu Server log is [here](https://ox.gluu.org/doku.php?id=ce:logs). Please feel free to check the status.

**Comment by willow9886** [comment]
@mzico is this ready to get transferred over to the docs?

**Comment by mzico** [comment]
@willow9886 : yes, let's do it.

**Comment by willow9886** [comment]
ok, moving on it.
