### ISSUE TITLE
Configuring Gluu Server with Centos 7.2

### ISSUE THREAD

**Issue by BitKris** [GluuFederation/docs#104]
Please help.  I am following the document https://gluu.org/docs/deployment/centos7/#installing-gluu-server and honestly its not working.  I can't seem to start the service gluu-serverd-2.4.3.  Here is everything that I have done.

[root@localhost ~]# /sbin/gluu-serverd-2.4.3 start
[root@localhost ~]# /sbin/gluu-serverd-2.4.3 stop
[root@localhost ~]# yum remove gluu-server-2.4.3
Loaded plugins: fastestmirror, langpacks
Resolving Dependencies
--> Running transaction check
---> Package gluu-server-2.4.3.x86_64 0:3-1.centos7 will be erased
--> Finished Dependency Resolution
Gluu-rpm-centos7-repo                                    | 2.9 kB     00:00     
base/7/x86_64                                            | 3.6 kB     00:00     
extras/7/x86_64                                          | 3.4 kB     00:00     
updates/7/x86_64                                         | 3.4 kB     00:00     

Dependencies Resolved

================================================================================
 Package              Arch      Version         Repository                 Size
================================================================================
Removing:
 gluu-server-2.4.3    x86_64    3-1.centos7     @Gluu-rpm-centos7-repo    1.6 G

Transaction Summary
================================================================================
Remove  1 Package

Installed size: 1.6 G
Is this ok [y/N]: y
Downloading packages:
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
Stopping Gluu Server ...
  Erasing    : gluu-server-2.4.3-3-1.centos7.x86_64                         1/1 
warning: file /opt/gluu-server-2.4.3/var/lib/rpm/__db.003: remove failed: No such file or directory
warning: file /opt/gluu-server-2.4.3/var/lib/rpm/__db.002: remove failed: No such file or directory
warning: file /opt/gluu-server-2.4.3/var/lib/rpm/__db.001: remove failed: No such file or directory
Your changes will be saved into /opt/gluu-server-2.4.3.rpm.saved
  Verifying  : gluu-server-2.4.3-3-1.centos7.x86_64                         1/1 

Removed:
  gluu-server-2.4.3.x86_64 0:3-1.centos7                                        

Complete!
[root@localhost ~]# yum remove gluu-server
Loaded plugins: fastestmirror, langpacks
Resolving Dependencies
--> Running transaction check
---> Package gluu-server.x86_64 0:2.3.6-27.el7.centos will be erased
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package       Arch     Version                  Repository                Size
================================================================================
Removing:
 gluu-server   x86_64   2.3.6-27.el7.centos      @Gluu-rpm-centos7-repo   1.4 G

Transaction Summary
================================================================================
Remove  1 Package

Installed size: 1.4 G
Is this ok [y/N]: y
Downloading packages:
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
Checking if Gluu Server isn't running...
  Erasing    : gluu-server-2.3.6-27.el7.centos.x86_64                       1/1 
Your changes will be saved into /opt/gluu-server.rpm.saved
  Verifying  : gluu-server-2.3.6-27.el7.centos.x86_64                       1/1 

Removed:
  gluu-server.x86_64 0:2.3.6-27.el7.centos                                      

Complete!
[root@localhost ~]# rm -rf /opt/gluu-server-2.4.3*
[root@localhost ~]# rm -rf /opt/gluu-server-2.4.3
[root@localhost ~]# rm -rf /opt/gluu-server*
[root@localhost ~]# rm -rf /opt/gluu-server
[root@localhost ~]# rm -rf /opt/gluu-server24.save
[root@localhost ~]# yum update
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: mirror.es.its.nyu.edu
 * extras: chicago.gaminghost.co
 * updates: mirror.netdepot.com
No packages marked for update
[root@localhost ~]# wget https://repo.gluu.org/centos/Gluu.repo -O /etc/yu,.repos.d/Gluu.repo
/etc/yu,.repos.d/Gluu.repo: No such file or directory
[root@localhost ~]# wget https://repo.gluu.org/centos/Gluu.repo -O /etc/yum.repos.d/Gluu.repo
--2016-07-13 17:03:40--  https://repo.gluu.org/centos/Gluu.repo
Resolving repo.gluu.org (repo.gluu.org)... 104.239.197.44
Connecting to repo.gluu.org (repo.gluu.org)|104.239.197.44|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-07-13 17:03:40 ERROR 404: Not Found.

[root@localhost ~]# wget https://repo.gluu[root@localhost ~]# wget https://repo.gluu.org/centos/Gluu-centos7.repo -O /etc/yum.repos.d/Gluu.repo
--2016-07-13 17:05:24--  https://repo.gluu.org/centos/Gluu-centos7.repo
Resolving repo.gluu.org (repo.gluu.org)... 104.239.197.44
Connecting to repo.gluu.org (repo.gluu.org)|104.239.197.44|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 159
Saving to: ‘/etc/yum.repos.d/Gluu.repo’

 0%  0           --.-K/s                  100% 159         --.-K/s   in 0s            

2016-07-13 17:05:24 (9.94 MB/s) - ‘/etc/yum.repos.d/Gluu.repo’ saved [159/159]

[root@localhost ~]# wget https://repo.gluu.org/centos/RPM-GPG-KEY-GLUU -O /etc/pki/rpm-gpg/RPM-GPG-KEY-GLUU
--2016-07-13 17:05:46--  https://repo.gluu.org/centos/RPM-GPG-KEY-GLUU
Resolving repo.gluu.org (repo.gluu.org)... 104.239.197.44
Connecting to repo.gluu.org (repo.gluu.org)|104.239.197.44|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3112 (3.0K)
Saving to: ‘/etc/pki/rpm-gpg/RPM-GPG-KEY-GLUU’

 0%  0           --.-K/s                  100% 3,112       --.-K/s   in 0s            

2016-07-13 17:05:46 (120 MB/s) - ‘/etc/pki/rpm-gpg/RPM-GPG-KEY-GLUU’ saved [3112/3112]

[root@localhost ~]# rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-GLUU
[root@localhost ~]# yum clean all
Loaded plugins: fastestmirror, langpacks
Cleaning repos: Gluu-rpm-centos7-repo base
              : extras updates
Cleaning up everything
Cleaning up list of fastest mirrors
[root@localhost ~]# yum install gluu-server-2.4.3
Loaded plugins: fastestmirror, langpacks
Gluu-rpm-centos7-r | 2.9 kB     00:00     
base               | 3.6 kB     00:00     
extras             | 3.4 kB     00:00     
updates            | 3.4 kB     00:00     
(1/5): extras/7/x86_ | 149 kB   00:00     
(2/5): base/7/x86_64 | 155 kB   00:00     
(3/5): Gluu-rpm-cent | 258 kB   00:00     
(4/5): updates/7/x86 | 5.7 MB   00:01     
(5/5): base/7/x86_64 | 5.3 MB   00:06     
Determining fastest mirrors
 * base: mirrors.lga7.us.voxel.net
 * extras: mirror.es.its.nyu.edu
 * updates: chicago.gaminghost.co
Resolving Dependencies
--> Running transaction check
---> Package gluu-server-2.4.3.x86_64 0:3-1.centos7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

==========================================
 Package
    Arch   Version
              Repository             Size
==========================================
Installing:
 gluu-server-2.4.3
    x86_64 3-1.centos7
              Gluu-rpm-centos7-repo 624 M

Transaction Summary
==========================================
Install  1 Package

Total download size: 624 M
Installed size: 1.6 G
Is this ok [y/d/N]: y
Downloading packages:
gluu-server-2.4.3-3- | 624 MB   05:57     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : gluu-server-2.4.3-3-   1/1 
  Verifying  : gluu-server-2.4.3-3-   1/1 

Installed:
  gluu-server-2.4.3.x86_64 0:3-1.centos7  

Complete!
[root@localhost ~]# /sbin/gluu-serverd-2.4.3 start
[root@localhost ~]# /gluu-serverd-2.4.3 start
bash: /gluu-serverd-2.4.3: No such file or directory
[root@localhost ~]# service gluu-serverd-2.4.3 start
Redirecting to /bin/systemctl start  gluu-serverd-2.4.3.service
Failed to start gluu-serverd-2.4.3.service: Unit gluu-serverd-2.4.3.service failed to load: No such file or directory.
[root@localhost ~]#

**Comment by mzico** [comment]
@BitKris : Please use our Support portal ( https://support.gluu.org ) for any kind of question or troubleshooting. Github is for bug reports.
