### ISSUE TITLE
Move Installation Docs to respective repositories

### ISSUE THREAD

**Issue by zamilskhan** [GluuFederation/docs#12]
I see that there are 2 repositories for Gluu CE in the following links.
https://github.com/GluuFederation/ce-centos
https://github.com/GluuFederation/ce-ubuntu
The installation instructions can be put in the two repositories or maybe point to the installation instructions for the two systems.

**Comment by yurem** [comment]
I added these 2 repos to track issues. I think we need to keep installation instruction in docs project only

**Comment by zamilskhan** [comment]
Okay, got it.
