### ISSUE TITLE
"Attribute mapping" not covered in public doc

### ISSUE THREAD

**Issue by mzico** [GluuFederation/docs#13]
"Attribute mapping" section (screenshot) is not covered in doc: http://www.gluu.org/docs/admin-guide/oxTrust/configuration/#cache-refresh

screenshot: 
![attribute_mapping](https://cloud.githubusercontent.com/assets/7156097/7089586/986190ac-df62-11e4-9eb9-055d999db207.png)

**Comment by willow9886** [comment]
fixed.
