### ISSUE TITLE
unable to install gluu server on REHL 7.2 : unpacking of archive failed on file /opt/gluu-server-2.4.4.2/var/lib/rpm/Packages;5841179d: cpio: read failed - No such file or directory

### ISSUE THREAD

**Issue by umapati** [GluuFederation/docs#146]
Hi, I am trying to install Gluu on my Development server siting inside the corporate LAN with no access to internet. i have done the following:

1.	Download gluu-server-2.4.4.2-1-1.rhel7.x86_64.rpm from internet
2.	Transfer to SIT using winscp
3.	Run rpm -i -vv gluu-server-2.4.4.2-1-1.rhel7.x86_64.rpm using root

But I get the following error:

XZDIO: 261724 reads, 2212069840 total bytes in 62.814077 secs
error: unpacking of archive failed on file /opt/gluu-server-2.4.4.2/var/lib/rpm/Packages;5841179d: cpio: read failed - No such file or directory

**Comment by mzico** [comment]
@umapati : Please feel free to use our Support portal ( https://support.gluu.org ) for any kind of support issue.
