### ISSUE TITLE
oxTrust attributes / create a wiki on attributes

### ISSUE THREAD

**Issue by mzico** [GluuFederation/docs#22]
Create a wiki on oxTrust attributes. 

A spreadsheet can be created primary to show: 

1. DisplayName of Attributes. 
2. Purpose of Attributes. ( SAML, OpenID Connect ).

**Comment by zamilskhan** [comment]
Created a page (http://ox.gluu.org/doku.php?id=oxtrust:attributes) for this purpose. I will be listing the available attributes and their purpose in the page.

**Comment by yurem** [comment]
http://www.gluu.org/docs/reference/ldap-schema/
Probably it's not up to date. This is latest schema: https://github.com/GluuFederation/community-edition-setup/blob/master/static/opendj/101-ox.ldif
