### ISSUE TITLE
Update oxTrust+oxAuth reference docs

### ISSUE THREAD

**Issue by mzico** [GluuFederation/docs#27]
We need to add more information here in: 

1. http://www.gluu.org/docs/reference/oxAuth/
2. http://www.gluu.org/docs/reference/oxTrust/

This reference docs should include the purpose, description of all oxAuth and oxTrust properties files.

**Comment by zamilskhan** [comment]
will it allow manually editing properties file and seeing the changes in GUI?

**Comment by mzico** [comment]
>> will it allow manually editing properties file and seeing the changes in GUI?

Of course. But the purpose of this doc is to explain what properties do what. The target audience: Developers.

**Comment by zamilskhan** [comment]
oxTrust JSON config page complete.

https://www.gluu.org/docs/gluu-defaults/oxtrust-properties/

**Comment by zamilskhan** [comment]
#23

**Comment by zamilskhan** [comment]
oxAuth docs are not necessary as the fields contain the explanation now.
