### ISSUE TITLE
ShibbolethSP-Windows-Apache doc incomplete

### ISSUE THREAD

**Issue by mzico** [GluuFederation/docs#28]
"Configuring Apache Shibboleth SP in Windows" section of doc ( http://www.gluu.org/docs/articles/apache-saml/ ) is incomplete. 

For reference, check this link: http://ox.gluu.org/doku.php?id=windows_sp_configuration#apache_configuration

**Comment by zamilskhan** [comment]
This was addressed while fixing the formatting.
