### ISSUE TITLE
Letsencrypt instructions

### ISSUE THREAD

**Issue by karlbateman** [GluuFederation/docs#3]
Could you provide some details about using LetsEncrypt for certificates as I have the "Your connection is not private" error with a fresh installation on Debian 8 with Gluu 3.0.0

**Comment by mzico** [comment]
@ganesh-at-wiw ....

**Comment by mzico** [comment]
@karlbateman : This doc isn't in our support scope but as we are using LetsEncrypt for own purpose so we will publish a doc on how to use this in Gluu Server. 

Stay tuned.

**Comment by willow9886** [comment]
There's a thread about this on Gluu Support: https://support.gluu.org/other/3758/replace-httpd-certificate-with-letsencrypt-generated-certificate/ 

Please direct any questions you may have there. 

Thanks!
