### ISSUE TITLE
Text / command formats are not correct 

### ISSUE THREAD

**Issue by mzico** [GluuFederation/docs#30]
'apache-saml' doc formatting is bad. As you can see formatting is bad. No header, no subheader etc. 
i.e.  #1 command is bigger than header, #3 'curl' command should be under #2 ( Grab shibboleth repository from SWITCH ), #3, Quick test command is on same line.... 
![format_doc](https://cloud.githubusercontent.com/assets/7156097/9443044/9a425eb8-4a44-11e5-99fe-2af47bd46677.png)

**Comment by zamilskhan** [comment]
The formatting is fixed and updated.
