### ISSUE TITLE
Key is fetched from plain http server, https certificate expired

### ISSUE THREAD

**Issue by rngadam** [GluuFederation/docs#32]
http://www.gluu.org/docs/admin-guide/deployment/ubuntu/

```
 # curl http://repo.gluu.org/ubuntu/gluu-apt.key | apt-key add - 
```

http instead of https. 

HTTPS server has:

```
This server could not prove that it is repo.gluu.org; its security certificate expired 147 day(s) ago. This may be caused by a misconfiguration or an attacker intercepting your connection. Your computer's clock is currently set to Friday, September 4, 2015. Does that look right? If not, you should correct your system's clock and then refresh this page.
```

seems a bit unsafe. Given the nature of what Gluu is used for, shouldn't *.gluu.org be https?

**Comment by mzico** [comment]
We are keeping our repo server HTTP for now.

**Comment by rngadam** [comment]
BTW, Letsencrypt is a way to obtain free HTTPS certificates:

http://letsencrypt.org/
https://github.com/letsencrypt/letsencrypt

**Comment by mzico** [comment]
Thanks, cert is not the issue, we have our own CA cert. We are keeping this HTTP by design for now.
