### ISSUE TITLE
Update 'Cache Refresh' doc for 2.4

### ISSUE THREAD

**Issue by mzico** [GluuFederation/docs#50]
Update doc to cover main menu of 'Cache Refresh': 

![admin_cache_menu](https://cloud.githubusercontent.com/assets/7156097/11339534/90745e64-91bf-11e5-9d64-4be4ca0efbf2.png)

**Comment by zamilskhan** [comment]
Updated the Cache Refresh doc to reflect new UI.

**Comment by mzico** [comment]
@zamilskhan : I can see 'non-syncing' ( not syncing with image and description ) issues there in CR doc.

**Comment by zamilskhan** [comment]
Fixed
