### ISSUE TITLE
Update 'Log Viewer' doc according to 2.4.x

### ISSUE THREAD

**Issue by mzico** [GluuFederation/docs#63]
Need to update: http://www.gluu.org/docs/admin-guide/configuration/#view-log-file

There is no 'Configure Log viewer' now.

**Comment by zamilskhan** [comment]
![screenshot-idp uaex edu 2016-01-13 00-11-21](https://cloud.githubusercontent.com/assets/7703245/12272408/8fc7ecc2-b98a-11e5-9297-3d3f3329ba5d.png)
This is a screenshot from the 2.4.1 build. I am not sure which "configure log viewer" is no longer there.

**Comment by mzico** [comment]
@zamilskhan : Yes.. "Configure log viewer" is there *but* in our 2.4.x series we are already giving user these four logs ( oxAuth, oxTrust, oxTrust CR and console ) by default. 
What I would want you to modify: 

1. We are already shipping four logs by default. ( attach new screenshot which has 'console' as well )
2. If user want to add 'more' logs, then can add it with 'Add log template'

That's it; just few more lines adding and change one screenshot.

**Comment by zamilskhan** [comment]
Updated: http://www.gluu.org/docs/admin-guide/configuration/#configure-log-viewer
Added: new screenshot with console

**Comment by mzico** [comment]
Thanks!
