### ISSUE TITLE
apache2 server restart getting failed

### ISSUE THREAD

**Issue by jacobsukumar** [GluuFederation/docs#64]
![apache2restart](https://cloud.githubusercontent.com/assets/12845308/12429394/029d5694-bf10-11e5-9aba-f73be7835044.PNG)

Tried restart the apache2 server as a service, I got error. Again tried to restart manually, it is giving same error.(attached screenshot)

**Comment by mzico** [comment]
@jacobsukumar: let's chat. This is not bug. This is more like a configuration issue in mod_auth_oidc
