### ISSUE TITLE
Update Salesforce doc

### ISSUE THREAD

**Issue by mzico** [GluuFederation/docs#68]
Replace this (**) image with attached one. 

New image: 

![salesforcetrustrelationshipgluuserver](https://cloud.githubusercontent.com/assets/7156097/13378587/85cd191c-ddd0-11e5-922e-2195841e98a8.png)

(**) https://raw.githubusercontent.com/GluuFederation/docs/master/sources/img/salesforce/Gluu_Server.png

**Comment by zamilskhan** [comment]
Updated in new docs.
