### ISSUE TITLE
Update 'User Registration' for enable/disable authn of new user

### ISSUE THREAD

**Issue by mzico** [GluuFederation/docs#71]
It's possible to 'enable' login for newly registered user with a feature in 2.4.2. By default, it's 'false' but making it 'true' and 'enabling' this registration script will allow new users to log into IDP without any kind of custom script. Update registration doc. 

Screenshot of this feature added below: 

![userenable](https://cloud.githubusercontent.com/assets/7156097/13641125/f65d1f88-e5dc-11e5-8295-d5ada54c43b7.png)

**Comment by zamilskhan** [comment]
@mzico added https://gluu.org/docs/cache-refresh/register/. Please check.
