### ISSUE TITLE
Add Certificate Authentication script

### ISSUE THREAD

**Issue by zamilskhan** [GluuFederation/docs#74]
Add the script in the Script Page.
https://github.com/GluuFederation/oxAuth/tree/master/Server/integrations/cert

**Comment by zamilskhan** [comment]
@nynymike added certificate authentication under person authentication page. @willow9886 it might be a good idea to use tables to define the properties in the other scripts.

**Comment by willow9886** [comment]
@zamilskhan yes agreed.
