### ISSUE TITLE
add instructions in oxPush 2MFA docs

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/docs#77]
On https://github.com/GluuFederation/docs/blob/master/sources/multi-factor/oxpush2.md

In the last instruction, "Change the default authentication method to oxPush2", you need to change both:   - Authentication mode
- oxTrust authentication mode

See screenshot:

![image](https://cloud.githubusercontent.com/assets/5271048/13883127/1aeba3b8-ecf6-11e5-8e69-798f2f26f827.png)

**Comment by zamilskhan** [comment]
Added.
