### ISSUE TITLE
Merge LDAP Attribute docs

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/docs#8]
For LDAP attribute, we have two pages in our doc:

1. http://www.gluu.org/docs/admin-guide/saml/outbound-saml/#ldap-attributes

2. http://www.gluu.org/docs/admin-guide/oxTrust/configuration/#attributes

#1 is more comprehensive than #2 ( as #1 also giving info on how to create custom attribute ).

Let's merge them.

**Comment by zamilskhan** [comment]
We cannot merge them as they are from two different tabs. However, while updating the docs, the attribute section of [1](http://www.gluu.org/docs/admin-guide/saml/outbound-saml/#ldap-attributes) will be transferred to [2](http://www.gluu.org/docs/admin-guide/oxTrust/configuration/#attributes) as it is not possible to add attributes from SAML--> Trust Relationshis.

**Comment by mzico** [comment]
@zamilskhan : Yes, better. In fact, just add "how to add a custom custom" attribute in #2 section [ before "Cache Refresh" part ]. That should serve our purpose even.

**Comment by adrian-gluu** [comment]
Can I build the pkgs for debian and centos? did you merge your repos into this one?
