### ISSUE TITLE
Documentation on 'Manage Sector Identifiers'

### ISSUE THREAD

**Issue by mzico** [GluuFederation/docs#82]
- What is 'Sector Identifiers'
- Why we need that
- How to operate

![sector_identifiers](https://cloud.githubusercontent.com/assets/7156097/14149089/1aaf2c6e-f668-11e5-91df-a8583af92e05.png)

**Comment by zamilskhan** [comment]
Note:
Sector identifier is a part of the redirect URL, used by the RP to compute unique identifier/nameID of the user for the openID client. This allows using a consistent NameID independent of domain names. This URI must reference a JSON file containing the redirect_uri(s).

**Comment by zamilskhan** [comment]
@mzico the sector identifier section is hidden for now.
