### ISSUE TITLE
Custom Script Page Cleanup

### ISSUE THREAD

**Issue by zamilskhan** [GluuFederation/docs#83]
Cleanup the custom script page to add information where necessary and use tables to make reading easier.

**Comment by willow9886** [comment]
Reference: [https://support.gluu.org/integrations/prepareforstep-not-called-on-step-2-2596#at9448](https://support.gluu.org/integrations/prepareforstep-not-called-on-step-2-2596#at9448)

**Comment by zamilskhan** [comment]
Used tables to represent methods.
