### ISSUE TITLE
Update 'Default Authentication Method' doc

### ISSUE THREAD

**Issue by mzico** [GluuFederation/docs#84]
Update: 
https://gluu.org/docs/oxtrust/configuration/#default-authentication-method

**Comment by willow9886** [comment]
reference: https://support.gluu.org/identity-management/default-authentication-method-2598

**Comment by zamilskhan** [comment]
Updated page.

**Comment by mzico** [comment]
@zamilskhan : 

> This mode is used while authenticating general users or synced users from backend LDAP/AD

Better say it like this way.... Gluu Server uses oxAuth as the first step of authentication in all kind of SSO protocols ( OpenID Connect, SAML, CAS ). Whenever anyone just authenticate with Gluu Server ( without entering into oxTrust ) for any RP/SP they use oxAuth only. 'Authentication Mode' defines that layer only. 

Here is an image which might help you to understand the difference between authentication modes. 

![authentication_mode_diff](https://cloud.githubusercontent.com/assets/7156097/14297268/9afd4808-fb43-11e5-8391-60f236a95b47.png)

**Comment by zamilskhan** [comment]
@mzico can you check now?

**Comment by mzico** [comment]
@zamilskhan lol... that's the beauty! You can encapsulate bunch of sentences and images into one statement.
