### ISSUE TITLE
Client registration documentation is about userinfo

### ISSUE THREAD

**Issue by Absor** [GluuFederation/docs#90]
Dynamic client registration endpoint documentation is currently about userinfo endpoint.

https://github.com/GluuFederation/docs/blob/master/sources/api/oic-register-client.md

**Comment by zamilskhan** [comment]
Note:
> https://alex.gluu.org/oxauth/seam/resource/restv1/oxauth/register

**Comment by zamilskhan** [comment]
Updated registration page.

**Comment by zamilskhan** [comment]
Complete update pushed.
