### ISSUE TITLE
How to create custom NameID in Gluu Server

### ISSUE THREAD

**Issue by mzico** [GluuFederation/docs#92]
Migrate this ( https://ox.gluu.org/doku.php?id=ce:custom_nameid ) doc to public 'www.gluu.org/docs'

**Comment by willow9886** [comment]
@zamilskhan this seems like something we can add into the new section "Tips & Tricks"

**Comment by zamilskhan** [comment]
@willow9886  we already have a section for [custom attributes](https://gluu.org/docs/customize/attributes/). That is the ideal place for this doc.

**Comment by willow9886** [comment]
ah OK, good call.

**Comment by zamilskhan** [comment]
Done.
