### ISSUE TITLE
Update doc 

### ISSUE THREAD

**Issue by mzico** [GluuFederation/docs#93]
@zamilskhan and @willow9886 : A proposal... do you think we can put '2.4.x' instead of specific '2.4.1' or '2.4.2' here in these two docs:

1. https://gluu.org/docs/deployment/upgrading/
2. All CE installation doc ( Ubuntu, CentOS... )

**Comment by zamilskhan** [comment]
@mzico I will update the upgrade page. What do you mean by 

> All CE installation doc ( Ubuntu, CentOS... )

**Comment by mzico** [comment]
Installation pages.. i.e. https://gluu.org/docs/deployment/rhel/ or https://gluu.org/docs/deployment/centos/

**Comment by zamilskhan** [comment]
won't that confuse people who are trying to install gluu server? we kept it like that so people can copy and paste the commands to install Gluu Server.

**Comment by mzico** [comment]
Might be... that's why asked what you guys think.. :-)

**Comment by aveekbu** [comment]
A proposal: The deployment guide sub menu could be: [this is an example]

- Deployment (by version)

1. Gluu Server 2.3.x
1.1 release note
1.2  OS specific
1.2.1 Debian/Ubuntu 14.04
1.2.2 CentOS/RHEL 6.x
1.2.3 CentOS/RHEL 7.x

2. Gluu Server 2.4.1
2.1 release note
2.2 OS specific
2.2.1 Debian/Ubuntu 14.04
2.2.2 RHEL/CentOS 6.x
2.2.3 RHEL/CentOS 7.x

3. Gluu Server 2.4.2[stable]
....
4. Gluu Server 2.4.3 [Latest]
....
5. Gluu Server 2.5 [Beta]
....

A thought: We can also release and maintain doc version same as the oxAuth/oxTrust/gluuCE for tracking the changes in docs as well. It is better if we can QA and contribute on the doc at the same time.

**Comment by zamilskhan** [comment]
Closing issue for now. We can revisit it later.
