### ISSUE TITLE
Upgrade script fails

### ISSUE THREAD

**Issue by zeroluck** [GluuFederation/docs#94]
Following [https://github.com/GluuFederation/docs/blob/master/sources/deployment/upgrading.md](url), when I execute `./import24.py backup_24` I see errors stopping Tomcat and OpenDJ. I'm upgrading from gluu-server24 to gluu-server-2.4.2.

```
GLUU.[root@localhost ~]# ./import24.py backup_24
INFO     Stopping Tomcat ...
sh: /usr/sbin/service: No such file or directory
INFO     Stopping Directory Server ...
sh: /usr/sbin/service: No such file or directory
CRITICAL OpenDJ did not stop properly... exiting. Check /opt/opendj/logs/errors
```

On CentOS in the gluu CHROOT in gluu-server-2.4.2, the service command is at /sbin/service, not /usr/sbin/service.

I am not sure if this will affect Ubuntu, but the relevant line in the script is here: https://github.com/GluuFederation/community-edition-setup/blob/master/static/scripts/import24.py#L29

**Comment by mzico** [comment]
@zeroluck : please open ticket in https://support.gluu.org; Gluu Engineers will help you to troubleshoot the issue. If it really a bug then we will able to open the issue in proper github tree.
