### ISSUE TITLE
Update screenshot

### ISSUE THREAD

**Issue by mzico** [GluuFederation/docs#95]
Update 'Configuration' doc ( https://gluu.org/docs/oxtrust/configuration/#configuration )
We don't have 'Manage Email Address' tab now. 

![old_configuration](https://cloud.githubusercontent.com/assets/7156097/14707171/cc0a9b16-0788-11e6-8a0f-4f075e5e2157.png)

**Comment by zamilskhan** [comment]
@mzico screenshot updated.
