### ISSUE TITLE
Please update path of SCIM 1.1 endpoints

### ISSUE THREAD

**Issue by uboznikov** [GluuFederation/docs#96]
In [SCIM 1.1](https://gluu.org/docs/api/scim-1.1/), please update `/host/seam/resource/restv1` to `/identity/seam/resource/restv1/scim/v1`, e.g.

`/identity/seam/resource/restv1/scim/v1/Users{rsid}`

**Comment by zamilskhan** [comment]
Updated. @uboznikov please check https://gluu.org/docs/api/scim-1.1/
