### ISSUE TITLE
mod_auth_openidc instructions missing SSL key / cert generation

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/docs#99]
https://gluu.org/docs/integrate/ubuntu-installation/

The above doc (and others probably) are not complete regarding SSL configuration. It is missing the part about generating the private key and certificate and enabling the default ssl site. 

Please reference these instructions: 
https://www.digitalocean.com/community/tutorials/how-to-create-a-ssl-certificate-on-apache-for-ubuntu-14-04

**Comment by zamilskhan** [comment]
Added instructions to generate SSL Certificate in Ubuntu and CentOS OpenID Module guides.

**Comment by zamilskhan** [comment]
Links updated: https://gluu.org/docs/integrate/ubuntu-installation/ and https://gluu.org/docs/integrate/centos-installation/
